name: zeffya_lints
description: "Custom lints"
version: 2.0.1

repository: https://github.com/zeffbtw/zeffya_lints
homepage: https://github.com/zeffbtw/zeffya_lints
issue_tracker: https://github.com/zeffbtw/zeffya_lints/issues
topics:
  - lints
  - linter
  - utils
  - analysis
  - analyzer

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  analysis_server_plugin: ^0.3.0
  analyzer: ">=9.0.0 <11.0.0"
  analyzer_plugin: ">=0.13.10 <0.15.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
