name: zeffya_lints
description: "Custom lints"
version: 1.1.0

repository: https://github.com/zeffbtw/zeffya_lints
homepage: https://github.com/zeffbtw/zeffya_lints
issue_tracker: https://github.com/zeffbtw/zeffya_lints/issues
topics:
  - lints
  - linter
  - utils
  - analysis
  - analyzer

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^8.4.0
  analyzer_plugin: ^0.13.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
