name: zeffya_lints_plugin
description: Analyzer plugin for zeffya_lints
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  zeffya_lints:
    path: ../..
  analyzer: ^8.4.0
  analyzer_plugin: ^0.13.10
